# -*- coding: utf-8 -*-
"""Copy of Intergration

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-Ymb7F_B16Zkqecx-nwnP9d7uBdrVfdo
"""

from google.colab import drive
drive.mount('/content/drive')

import tensorflow as tf
from tensorflow.keras.preprocessing import image
import numpy as np

# =============================
# LOAD MODELS
# =============================
model1 = tf.keras.models.load_model(
    "/content/drive/MyDrive/Rice Leaf Project/models/best_model.h5"
)

model2 = tf.keras.models.load_model(
    "/content/drive/MyDrive/Rice Leaf Project/models/best_model2.h5"
)

# ⚠️ MUST match model-2 training order
disease_classes = ['Brown_Spot', 'Rice_Blast']

# =============================
# PREDICT ONE IMAGE
# =============================
def predict_single_image(img_path,
                         healthy_threshold=0.8,
                         disease_threshold=0.7):

    img = image.load_img(img_path, target_size=(224,224))
    img_array = image.img_to_array(img) / 255.0
    img_array = np.expand_dims(img_array, axis=0)

    # ---------- Model 1 ----------
    healthy_prob = model1.predict(img_array, verbose=0)[0][0]

    # Strong Healthy decision
    if healthy_prob >= healthy_threshold:
        return {
            "Healthy": healthy_prob,
            "Rice_Blast": 0.0,
            "Brown_Spot": 0.0,
            "Unknown": 0.0
        }

    # ---------- Model 2 ----------
    disease_probs = model2.predict(img_array, verbose=0)[0]
    class_idx = np.argmax(disease_probs)
    confidence = disease_probs[class_idx]

    if confidence >= disease_threshold:
        return {
            "Healthy": 0.0,
            disease_classes[class_idx]: confidence,
            "Brown_Spot" if disease_classes[class_idx] == "Rice_Blast" else "Rice_Blast": 0.0,
            "Unknown": 0.0
        }
    else:
        return {
            "Healthy": 0.0,
            "Rice_Blast": 0.0,
            "Brown_Spot": 0.0,
            "Unknown": confidence
        }

# =============================
# PREDICT 5 IMAGES
# =============================
def predict_five_images(image_paths):

    total_probs = {
        "Healthy": 0.0,
        "Rice_Blast": 0.0,
        "Brown_Spot": 0.0,
        "Unknown": 0.0
    }

    for path in image_paths:
        result = predict_single_image(path)
        for key in total_probs:
            total_probs[key] += result[key]

    # Average probabilities
    avg_probs = {k: v / len(image_paths) for k, v in total_probs.items()}

    # Final prediction
    final_class = max(avg_probs, key=avg_probs.get)
    final_confidence = avg_probs[final_class] * 100

    # =============================
    # OUTPUT
    # =============================
    print("\n===== AVERAGE PROBABILITIES =====")
    for key, value in avg_probs.items():
        print(f"{key}: {value:.4f}")

    print("\n===== FINAL RESULT =====")
    print(f"Final Prediction: {final_class} {final_confidence:.0f}%")

    return avg_probs, final_class, final_confidence

# =============================
# EXAMPLE: 5 USER INPUT IMAGES
# =============================
image_list = [
    "/content/drive/MyDrive/Rice Leaf Project/Testing/Testing_Diseased_Leaf/BS/Brown_spot  (254).jpg",
    "/content/drive/MyDrive/Rice Leaf Project/Testing/Testing_Diseased_Leaf/BS/Brown_spot  (259).jpg",
    "/content/drive/MyDrive/Rice Leaf Project/Testing/Testing_Diseased_Leaf/BS/Brown_spot  (269).jpg",
    "/content/drive/MyDrive/Rice Leaf Project/Testing/Testing_Diseased_Leaf/RB/original_20230705_121944.jpg",
    "/content/drive/MyDrive/Rice Leaf Project/Testing/Testing_Diseased_Leaf/RB/original_20230705_122709.jpg"
]

predict_five_images(image_list)

import tensorflow as tf
from google.colab import drive

# 1️⃣ Mount Google Drive
drive.mount('/content/drive')

# ===============================
# Model 1 – Healthy Model
# ===============================
model1 = tf.keras.models.load_model(
    "/content/drive/MyDrive/Rice Leaf Project/models/best_model.h5"
)

converter1 = tf.lite.TFLiteConverter.from_keras_model(model1)
tflite_model1 = converter1.convert()

with open("/content/drive/MyDrive/Rice Leaf Project/models/model_healthy.tflite", "wb") as f:
    f.write(tflite_model1)

print("✅ model_healthy.tflite saved to Google Drive")

# ===============================
# Model 2 – Disease Model
# ===============================
model2 = tf.keras.models.load_model(
    "/content/drive/MyDrive/Rice Leaf Project/models/best_model2.h5"
)

converter2 = tf.lite.TFLiteConverter.from_keras_model(model2)
tflite_model2 = converter2.convert()

with open("/content/drive/MyDrive/Rice Leaf Project/models/model_disease.tflite", "wb") as f:
    f.write(tflite_model2)

print("✅ model_disease.tflite saved to Google Drive")

print("🎉 Both TFLite models successfully converted and saved!")