# -*- coding: utf-8 -*-
"""Copy of Rice_Blast_vs_Brown_Spot

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ILJvePKyYJvBFA7Pw8xAXJLYhyeYfkEP
"""

from google.colab import drive
drive.mount('/content/drive')

import os
import shutil
import random
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.applications import MobileNet
from tensorflow.keras.layers import Dense, GlobalAveragePooling2D, Dropout, BatchNormalization
from tensorflow.keras.models import Model
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau, ModelCheckpoint
from tensorflow.keras.regularizers import l2
import matplotlib.pyplot as plt
import numpy as np

DATASET_PATH = "/content/drive/MyDrive/Rice Leaf Project/Dataset/Diseased_Leaf"
SPLIT_PATH = "/content/drive/MyDrive/Rice Leaf Project/Dataset/Split_Data"
MODEL_PATH = "/content/drive/MyDrive/Rice Leaf Project/models/best_model2.h5"

IMG_SIZE = (224,224)
BATCH_SIZE = 8
EPOCHS = 40

# CREATE TRAIN/VAL FOLDERS
# ==========================

classes = ["Rice_Blast", "Brown_Spot"]

for split in ["train", "val"]:
    for cls in classes:
        os.makedirs(os.path.join(SPLIT_PATH, split, cls), exist_ok=True)

# ==========================
# BALANCED 80/20 SPLIT
# ==========================

for cls in classes:
    class_path = os.path.join(DATASET_PATH, cls)
    images = os.listdir(class_path)
    random.shuffle(images)

    train_images = images[:200]   # 80%
    val_images = images[200:250]  # 20%

    for img in train_images:
        shutil.copy(
            os.path.join(class_path, img),
            os.path.join(SPLIT_PATH, "train", cls, img)
        )

    for img in val_images:
        shutil.copy(
            os.path.join(class_path, img),
            os.path.join(SPLIT_PATH, "val", cls, img)
        )

print("Balanced Split Done ✅")

train_datagen = ImageDataGenerator(
    rescale=1./255,
    rotation_range=30,
    zoom_range=0.2,
    width_shift_range=0.2,
    height_shift_range=0.2,
    brightness_range=[0.8,1.2],
    horizontal_flip=True,
    fill_mode='nearest'
)

val_datagen = ImageDataGenerator(rescale=1./255)

train_data = train_datagen.flow_from_directory(
    os.path.join(SPLIT_PATH, "train"),
    target_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    class_mode='categorical',
    shuffle=True
)

val_data = val_datagen.flow_from_directory(
    os.path.join(SPLIT_PATH, "val"),
    target_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    class_mode='categorical',
    shuffle=False
)

print(train_data.class_indices)

base_model = MobileNet(
    weights='imagenet',
    include_top=False,
    input_shape=(224,224,3)
)

# Freeze most layers
for layer in base_model.layers[:-20]:
    layer.trainable = False

for layer in base_model.layers[-20:]:
    layer.trainable = True

x = base_model.output
x = GlobalAveragePooling2D()(x)
x = BatchNormalization()(x)
x = Dense(64, activation='relu', kernel_regularizer=l2(0.001))(x)
x = Dropout(0.5)(x)
output = Dense(2, activation='softmax')(x)

model = Model(inputs=base_model.input, outputs=output)

model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=5e-5),
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

early_stop = EarlyStopping(
    monitor='val_loss',
    patience=7,
    restore_best_weights=True
)

reduce_lr = ReduceLROnPlateau(
    monitor='val_loss',
    factor=0.3,
    patience=4,
    min_lr=1e-6,
    verbose=1
)

checkpoint = ModelCheckpoint(
    MODEL_PATH,
    monitor='val_loss',
    save_best_only=True,
    verbose=1
)

history = model.fit(
    train_data,
    validation_data=val_data,
    epochs=EPOCHS,
    callbacks=[early_stop, reduce_lr, checkpoint]
)

# ==============================
# ACCURACY & LOSS GRAPH
# ==============================

plt.figure()
plt.plot(history.history['accuracy'])
plt.plot(history.history['val_accuracy'])
plt.title('Model Accuracy')
plt.ylabel('Accuracy')
plt.xlabel('Epoch')
plt.legend(['Train', 'Validation'])
plt.show()

plt.figure()
plt.plot(history.history['loss'])
plt.plot(history.history['val_loss'])
plt.title('Model Loss')
plt.ylabel('Loss')
plt.xlabel('Epoch')
plt.legend(['Train', 'Validation'])
plt.show()

# ==============================
# CONFUSION MATRIX (BLUE COLOR)
# ==============================

from sklearn.metrics import confusion_matrix, classification_report
import seaborn as sns

# Get true labels
true_labels = val_data.classes

# Predict
pred_probs = model.predict(val_data)
pred_labels = np.argmax(pred_probs, axis=1)

# Confusion matrix
cm = confusion_matrix(true_labels, pred_labels)

# Plot with blue color
plt.figure(figsize=(6,5))
sns.heatmap(cm, annot=True, fmt='d', cmap="Blues",
            xticklabels=val_data.class_indices.keys(),
            yticklabels=val_data.class_indices.keys())
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
plt.show()

# Classification report
print(classification_report(true_labels, pred_labels,
                            target_names=val_data.class_indices.keys()))

# ==============================
# PREDICTION FUNCTION WITH IMAGE INPUT
# ==============================
from tensorflow.keras.models import load_model
# Load model
model = load_model('/content/drive/MyDrive/Rice Leaf Project/models/best_model2.h5')

from tensorflow.keras.preprocessing import image
import numpy as np

# 🔹 Path to your test image
test_image_path = "/content/drive/MyDrive/Rice Leaf Project/Testing/Testing_Diseased_Leaf/RB/original_20230705_121944.jpg"  # <-- Replace with your image path

def predict_disease(img_path=test_image_path, threshold=0.7):
    # Load and preprocess image
    img = image.load_img(img_path, target_size=(224,224))
    img_array = image.img_to_array(img)
    img_array = img_array / 255.0
    img_array = np.expand_dims(img_array, axis=0)

    # Predict
    prediction = model.predict(img_array)

    confidence = np.max(prediction)
    class_index = np.argmax(prediction)

    class_names = list(train_data.class_indices.keys())
    predicted_class = class_names[class_index]

    # Unknown class if confidence < threshold
    if confidence < threshold:
        final_class = "Unknown Disease"
    else:
        final_class = predicted_class

    # Print results
    print("Prediction:", final_class)
    print("Confidence: {:.2f}%".format(confidence * 100))

    return final_class, confidence

# ==============================
# RUN PREDICTION
# ==============================
predict_disease()