# -*- coding: utf-8 -*-
"""Copy of Healthy_vs_Diseased

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CEymYRRpLGcaNmqAUl0-QhJ9ZDSQL8Dg
"""

from google.colab import drive
drive.mount('/content/drive')

import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.applications import MobileNet
from tensorflow.keras.layers import Dense, GlobalAveragePooling2D, Dropout
from tensorflow.keras.models import Model, load_model
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau, ModelCheckpoint
from sklearn.utils.class_weight import compute_class_weight
import numpy as np
import matplotlib.pyplot as plt

DATASET_PATH = "/content/drive/MyDrive/Rice Leaf Project/Dataset"
MODEL_PATH = "/content/drive/MyDrive/Rice Leaf Project/models/best_model.h5"

IMG_SIZE = (224, 224)
BATCH_SIZE = 16
EPOCHS = 25   # reduced slightly to prevent overfitting

# Training data (augmentation ON)
train_datagen = ImageDataGenerator(
    rescale=1./255,
    validation_split=0.2,
    rotation_range=20,
    zoom_range=0.15,
    width_shift_range=0.1,
    height_shift_range=0.1,
    brightness_range=[0.9, 1.1],
    horizontal_flip=True
)

# Validation data (NO augmentation)
val_datagen = ImageDataGenerator(
    rescale=1./255,
    validation_split=0.2
)

train_data = train_datagen.flow_from_directory(
    DATASET_PATH,
    target_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    class_mode='binary',
    subset='training',
    shuffle=True
)

val_data = val_datagen.flow_from_directory(
    DATASET_PATH,
    target_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    class_mode='binary',
    subset='validation',
    shuffle=False
)

classes = np.unique(train_data.classes)

class_weights = compute_class_weight(
    class_weight='balanced',
    classes=classes,
    y=train_data.classes
)

class_weight_dict = dict(zip(classes, class_weights))
print("Class weights:", class_weight_dict)

"""class weight = total samples / number of classes × samples in class (650/2 * 150 = 2.17) (650/2 * 500 =0.65 )"""

base_model = MobileNet(
    weights='imagenet',
    include_top=False,
    input_shape=(224,224,3)
)

base_model.trainable = False  # freeze CNN

x = base_model.output
x = GlobalAveragePooling2D()(x)
x = Dense(128, activation='relu')(x)
x = Dropout(0.4)(x)   # slightly reduced dropout (balanced)
output = Dense(1, activation='sigmoid')(x)

model = Model(inputs=base_model.input, outputs=output)

model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-4),
    loss='binary_crossentropy',
    metrics=['accuracy']
)

early_stop = EarlyStopping(
    monitor='val_loss',
    patience=5,
    restore_best_weights=True
)

reduce_lr = ReduceLROnPlateau(
    monitor='val_loss',
    factor=0.5,
    patience=3,
    min_lr=1e-6,
    verbose=1
)

checkpoint = ModelCheckpoint(
    MODEL_PATH,
    monitor='val_loss',
    save_best_only=True,
    verbose=1
)

history = model.fit(
    train_data,
    validation_data=val_data,
    epochs=EPOCHS,
    class_weight=class_weight_dict,
    callbacks=[early_stop, reduce_lr, checkpoint]
)

plt.figure(figsize=(12,5))

plt.subplot(1,2,1)
plt.plot(history.history['accuracy'], label='Train Accuracy')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy')
plt.legend()
plt.title("Accuracy")

plt.subplot(1,2,2)
plt.plot(history.history['loss'], label='Train Loss')
plt.plot(history.history['val_loss'], label='Validation Loss')
plt.legend()
plt.title("Loss")

plt.show()

best_model = load_model(MODEL_PATH)

from tensorflow.keras.preprocessing import image

img_path = "/content/drive/MyDrive/Extra images/H/Healthy_rice_leaf  (151).jpg"

img = image.load_img(img_path, target_size=(224,224))
img_array = image.img_to_array(img) / 255.0
img_array = np.expand_dims(img_array, axis=0)

prediction = best_model.predict(img_array)
pred_class = int(prediction[0][0] > 0.5)

result = "Healthy" if pred_class == 1 else "Diseased"
print("Prediction:", result)

from sklearn.metrics import confusion_matrix, classification_report
import seaborn as sns

# Get true labels
y_true = val_data.classes

# Predict probabilities
y_pred_prob = best_model.predict(val_data)

# Convert probabilities to class labels (0 or 1)
y_pred = (y_pred_prob > 0.5).astype(int).reshape(-1)

print("Predictions done!")

from sklearn.metrics import confusion_matrix, classification_report
import matplotlib.pyplot as plt
import seaborn as sns

# Steps to cover all validation samples
val_steps = val_data.samples // val_data.batch_size
if val_data.samples % val_data.batch_size != 0:
    val_steps += 1

# Predict probabilities
y_pred_prob = best_model.predict(val_data, steps=val_steps)

# Convert to class labels
y_pred = (y_pred_prob > 0.5).astype(int).reshape(-1)

# Trim extra predictions if any
y_pred = y_pred[:len(val_data.classes)]
y_true = val_data.classes

# Confusion Matrix
cm = confusion_matrix(y_true, y_pred)
plt.figure(figsize=(6,5))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=val_data.class_indices.keys(),
            yticklabels=val_data.class_indices.keys())
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title('Confusion Matrix')
plt.show()

# Classification report
report = classification_report(y_true, y_pred, target_names=val_data.class_indices.keys())
print(report)

model = load_model(MODEL_PATH)

# Unfreeze whole model first
model.trainable = True

# Freeze first 100 layers
for layer in model.layers[:100]:
    layer.trainable = False

model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-5),
    loss='binary_crossentropy',
    metrics=['accuracy']
)

early_stop = EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)

reduce_lr = ReduceLROnPlateau(monitor='val_loss',
                              factor=0.5,
                              patience=3,
                              min_lr=1e-6,
                              verbose=1)

checkpoint = ModelCheckpoint(MODEL_PATH,
                             monitor='val_loss',
                             save_best_only=True,
                             verbose=1)

history_fine = model.fit(
    train_data,
    validation_data=val_data,
    epochs=20,
    callbacks=[early_stop, reduce_lr, checkpoint]
)

# 🔹 Import required metrics
from sklearn.metrics import confusion_matrix, classification_report
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

# 🔹 Predict on validation set
y_pred_prob = best_model.predict(val_data)

# Convert probabilities to class labels
y_pred = (y_pred_prob > 0.5).astype(int).reshape(-1)

# True labels
y_true = val_data.classes

# 🔹 Create Confusion Matrix
cm = confusion_matrix(y_true, y_pred)

# 🔹 Plot
plt.figure(figsize=(6,5))
sns.heatmap(cm,
            annot=True,
            fmt='d',
            cmap='Blues',
            xticklabels=val_data.class_indices.keys(),
            yticklabels=val_data.class_indices.keys())

plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
plt.show()

# 🔹 Print Classification Report
print(classification_report(y_true, y_pred))

from tensorflow.keras.preprocessing import image
import numpy as np

# 🔹 Path to your image
img_path = "/content/drive/MyDrive/Rice Leaf Project/Dataset/Diseased_Leaf/Rice_Blast/Rice_blast  (5).jpg"

# 🔹 Load and preprocess image
img = image.load_img(img_path, target_size=(224,224))
img_array = image.img_to_array(img) / 255.0       # normalize
img_array = np.expand_dims(img_array, axis=0)    # add batch dimension

# 🔹 Predict
prediction_prob = best_model.predict(img_array)[0][0]

# 🔹 Decide class
pred_class = "Healthy" if prediction_prob > 0.5 else "Diseased"

# 🔹 Print result with confidence
confidence = prediction_prob if pred_class=="Healthy" else 1-prediction_prob
confidence_percent = confidence * 100

print(f"Prediction: {pred_class}")
print(f"Confidence: {confidence_percent:.2f}%")